# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"demo_code": "00_core.ipynb",
         "hw_cairo": "01_Cairo_Hello.ipynb",
         "surface_to_npy": "01_Cairo_Hello.ipynb",
         "surface_to_PIL": "01_Cairo_Hello.ipynb",
         "display_surface": "01_Cairo_Hello.ipynb"}

modules = ["core.py"]

doc_url = "https://johnowhitaker.github.io/days_of_code/"

git_url = "https://github.com/johnowhitaker/days_of_code/tree/master/"

def custom_doc_links(name): return None
